BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "DiaReparto" (
	"Id"	INTEGER NOT NULL,
	"Dia"	TEXT NOT NULL,
	"Estado"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Producto" (
	"Id"	INTEGER NOT NULL,
	"Nombre"	TEXT NOT NULL,
	"Precio"	REAL NOT NULL,
	"Estado"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Venta" (
	"Id"	INTEGER NOT NULL,
	"ProductoId"	INTEGER NOT NULL,
	"Cantidad"	INTEGER NOT NULL,
	"Estado"	TEXT NOT NULL,
	FOREIGN KEY("ProductoId") REFERENCES "Producto"("Id"),
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "ProdVendido" (
	"Id"	INTEGER NOT NULL,
	"ProductoId"	INTEGER NOT NULL,
	"NotaDeEnvioId"	INTEGER,
	"RegistroVentaId"	INTEGER,
	"PedidoId"	INTEGER,
	"Cantidad"	INTEGER NOT NULL,
	"Descripcion"	TEXT NOT NULL,
	"Precio"	REAL NOT NULL,
	"Estado"	TEXT NOT NULL,
	FOREIGN KEY("PedidoId") REFERENCES "Pedido"("Id"),
	FOREIGN KEY("ProductoId") REFERENCES "Producto"("Id"),
	FOREIGN KEY("RegistroVentaId") REFERENCES "RegistroVenta"("Id"),
	FOREIGN KEY("NotaDeEnvioId") REFERENCES "NotaDeEnvio"("Id"),
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Reparto" (
	"Id"	INTEGER NOT NULL,
	"Nombre"	TEXT NOT NULL,
	"DiaRepartoId"	INTEGER NOT NULL,
	"TA"	INTEGER NOT NULL,
	"TE"	INTEGER NOT NULL,
	"TD"	INTEGER NOT NULL,
	"TT"	INTEGER NOT NULL,
	"TAE"	INTEGER NOT NULL,
	"TotalB"	INTEGER NOT NULL,
	"TL"	INTEGER NOT NULL,
	"Estado"	TEXT NOT NULL,
	FOREIGN KEY("DiaRepartoId") REFERENCES "DiaReparto"("Id"),
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "RegistroVenta" (
	"Id"	INTEGER NOT NULL,
	"ClienteId"	INTEGER NULL,
	"NombreCliente"	TEXT NOT NULL,
	"Fecha"	TEXT NOT NULL,
	"Estado"	TEXT NOT NULL,
	FOREIGN KEY("ClienteId") REFERENCES "Cliente"("Id"),
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Recibo" (
	"Id"	INTEGER NOT NULL,
	"ClienteId"	INTEGER NOT NULL,
	"Fecha"	TEXT NOT NULL,
	"Impreso"	INTEGER NOT NULL,
	"DireccionCliente"	TEXT NOT NULL,
	"ImporteTotal"	REAL NOT NULL,
	"Estado"	TEXT NOT NULL,
	FOREIGN KEY("ClienteId") REFERENCES "Cliente"("Id"),
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "NotaDeEnvio" (
	"Id"	INTEGER NOT NULL,
	"ClienteId"	INTEGER NOT NULL,
	"Fecha"	TEXT NOT NULL,
	"Impresa"	INTEGER NOT NULL,
	"Detalle"	TEXT NOT NULL,
	"ImporteTotal"	REAL NOT NULL,
	"Estado"	TEXT NOT NULL,
	FOREIGN KEY("ClienteId") REFERENCES "Cliente"("Id"),
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "DetalleRecibo" (
	"Id"	INTEGER NOT NULL,
	"ReciboId"	INTEGER NOT NULL,
	"Detalle"	TEXT NOT NULL,
	"Importe"	REAL NOT NULL,
	"Estado"	TEXT NOT NULL,
	FOREIGN KEY("ReciboId") REFERENCES "Recibo"("Id"),
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Pedido" (
	"Id"	INTEGER NOT NULL,
	"Direccion"	TEXT NOT NULL,
	"ClienteId"	INTEGER NOT NULL,
	"RepartoId"	INTEGER NOT NULL,
	"Entregar"	INTEGER NOT NULL,
	"L"	INTEGER NOT NULL,
	"A"	INTEGER NOT NULL,
	"E"	INTEGER NOT NULL,
	"D"	INTEGER NOT NULL,
	"T"	INTEGER NOT NULL,
	"AE"	INTEGER NOT NULL,
	"ProductosText"	TEXT NOT NULL,
	"Estado"	TEXT NOT NULL,
	FOREIGN KEY("ClienteId") REFERENCES "Cliente"("Id"),
	FOREIGN KEY("RepartoId") REFERENCES "Reparto"("Id"),
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Cliente" (
	"Id"	INTEGER NOT NULL,
	"Direccion"	TEXT NOT NULL,
	"CodigoPostal"	TEXT,
	"Telefono"	TEXT,
	"Nombre"	TEXT,
	"CUIT"	TEXT,
	"Tipo"	TEXT,
	"Estado"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
COMMIT;
